- name: Deploy Dockerized Flask App
  hosts: remote
  become: true

  tasks:
    - name: Copy Docker image to remote
      copy:
        src: ./flask-app.tar
        dest: /tmp/flask-app.tar

    - name: Load Docker image on remote
      command: docker load -i /tmp/flask-app.tar

    - name: Stop existing container (if running)
      ignore_errors: true
      command: docker stop flask-app

    - name: Remove old container (if exists)
      ignore_errors: true
      command: docker rm flask-app

    - name: Run new Docker container
      command: docker run -d --name flask-app -p 80:80 flask-app:latest
